#!/bin/sh
# https://manpages.debian.org/unstable/live-build/lb_config.1.en.html

set -e
echo "Executing auto/config"
lb config noauto \
	--architecture amd64 \
	--distribution trixie \
	--archive-areas "main contrib non-free non-free-firmware" \
        --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
        --bootappend-live "live components locales=nl_BE.UTF-8 timezone=Europe/Brussels keyboard-layouts=be,nl keyboard-variants=,us overlay-size=50% swap=false hostname=TempOS quiet splash" \
        --memtest memtest86+ \
        --image-name TempOS \
        --chroot-squashfs-compression-level 18 \
        --chroot-squashfs-compression-type zstd \
	"${@}"
#        --binary-image hdd \
# WARNING: bootappend-live is overwritten in config/bootloaders custom menu. Repeat the options there. --bootappend-live has effectively no effect here

# all kernel parameters: https://docs.kernel.org/admin-guide/kernel-parameters.html

# --bootappend-live options:
# https://manpages.debian.org/unstable/live-config-doc/live-config.7.en.html
# https://manpages.debian.org/unstable/live-boot-doc/live-boot.7.en.html
# hostname=HOSTNAME
# username=USERNAME

# Graphics issues
# i915.modeset=0

# i915 parameters
# i915.modeset, "Use kernel modesetting [KMS] (0=disable, 1=on, -1=force vga console preference [default])");
# i915.panel_ignore_lid, "Override lid status (0=autodetect, 1=autodetect disabled [default], -1=force lid closed, -2=force lid open)");
# i915.semaphores, "Use semaphores for inter-ring sync (default: -1 (use per-chip defaults))");
# i915.enable_rc6, "Enable power-saving render C-state 6. Different stages can be selected via bitmask values (0 = disable; 1 = enable rc6; 2 = enable deep rc6; 4 = enable deepest rc6). For example, 3 would enable rc6 and deep rc6, and 7 would enable everything. default: -1 (use per-chip default)");
# i915.enable_dc, "Enable power-saving display C-states. (-1=auto [default]; 0=disable; 1=up to DC5; 2=up to DC6)");
# i915.enable_fbc, "Enable frame buffer compression for power savings (default: -1 (use per-chip default))");
# i915.lvds_channel_mode, "Specify LVDS channel mode (0=probe BIOS [default], 1=single-channel, 2=dual-channel)");
# i915.lvds_use_ssc, "Use Spread Spectrum Clock with panels [LVDS/eDP] (default: auto from VBT)");
# i915.vbt_sdvo_panel_type, "Override/Ignore selection of SDVO panel mode in the VBT (-2=ignore, -1=auto [default], index in VBT BIOS table)");
# i915.reset, "Attempt GPU resets (default: true)");
# i915.enable_hangcheck, "Periodically check GPU activity for detecting hangs. WARNING: Disabling this can cause system wide hangs. (default: true)");
# i915.enable_ppgtt, "Override PPGTT usage. (-1=auto [default], 0=disabled, 1=aliasing, 2=full, 3=full with extended address space)");
# i915.enable_execlists, "Override execlists usage. (-1=auto [default], 0=disabled, 1=enabled)");
# i915.enable_psr, "Enable PSR (default: 1) (0=disabled [default], 1=link-off maximum power-savings, 2=link-standby mode) In case you needed to force it on standby or disabled, please report PCI device ID, subsystem vendor and subsystem device ID to intel-gfx@lists.freedesktop.org, if your machine needs it. It will then be included in an upcoming module version.");
# i915.preliminary_hw_support, "Enable preliminary hardware support.");
# i915.disable_power_well, "Disable display power wells when possible (-1=auto [default], 0=power wells always on, 1=power wells disabled when possible)");
# i915.enable_ips, "Enable IPS (default: true)");
# i915.fastboot, "Try to skip unnecessary mode sets at boot time (default: false)");
# i915.prefault_disable, "Disable page prefaulting for pread/pwrite/reloc (default:false). For developers only.");
# i915.load_detect_test, "Force-enable the VGA load detect code for testing (default:false). For developers only.");
# i915.invert_brightness, "Invert backlight brightness (-1 force normal, 0 machine defaults, 1 force inversion), please report PCI device ID, subsystem vendor and subsystem device ID to dri-devel@lists.freedesktop.org, if your machine needs it. It will then be included in an upcoming module version.");
# i915.disable_display, "Disable display (default: false)");
# i915.disable_vtd_wa, "Disable all VT-d workarounds (default: false)");
# i915.enable_cmd_parser, "Enable command parsing (1=enabled [default], 0=disabled)");
# i915.use_mmio_flip, "use MMIO flips (-1=never, 0=driver discretion [default], 1=always)");
# i915.mmio_debug, "Enable the MMIO debug code for the first N failures (default: off). This may negatively affect performance.");
# i915.verbose_state_checks, "Enable verbose logs (ie. WARN_ON()) in case of unexpected hw state conditions.");
# i915.edp_vswing, "Ignore/Override vswing pre-emph table selection from VBT (0=use value from vbt [default], 1=low power swing(200mV), 2=default swing(400mV))");
# i915.edp_vswing, "Ignore/Override vswing pre-emph table selection from VBT (0=use value from vbt [default], 1=low power swing(200mV), 2=default swing(400mV))");
# i915.enable_dp_mst,	"Enable multi-stream transport (MST) for new DisplayPort sinks. (default: true)");
